name: render
on:
  push:
    branches:
      - main
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: cuchi/jinja2-action@v1.2.0
        name: Build publish/index.html from timeline-visjs.jinja.
        with:
          data_file: data.yml
          template: timeline-visjs.jinja
          output_file: publish/index.html

      - uses: cuchi/jinja2-action@v1.2.0
        name: Build publish/static.html from timeline-static.jinja.
        with:
          data_file: data.yml
          template: timeline-static.jinja
          output_file: publish/static.html


      - name: Deploy 🚀
        if: ${{ !env.ACT }}
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: publish/ # The folder the action should deploy.
